/*
PingOne Advanced Identity Cloud API

## Introduction The PingOne Advanced Identity Cloud REST API lets you manage your Advanced Identity Cloud tenants. The API exposes access management and identity management endpoints, with additional endpoints specific to Advanced Identity Cloud tenant environments.<br /><br /> We are now publishing the API spec in OpenAPI 3.0. For the legacy Swagger 2.0 spec, please download [swagger.yaml](swagger.yaml), but note that it may not contain all new functionality.<br /><br /> For full PingOne Advanced Identity Cloud documentation, please visit [the docs website](https://docs.pingidentity.com/pingoneaic/latest/). ## Authenticating to the API The PingOne Advanced Identity Cloud REST API has two different authentication methods:   - [API key and secret](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-api-key-and-secret.html): used for tenant read-only operations  - [Access token](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-access-token.html): used for access management operations, identity management operations or tenant write operations  For a summary of how to use these authentication methods, refer to [Authenticate to Advanced Identity Cloud REST API](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-overview.html).

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aic

import (
	"encoding/json"
)

// checks if the PromotionLockStateLowerEnv type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromotionLockStateLowerEnv{}

// PromotionLockStateLowerEnv struct for PromotionLockStateLowerEnv
type PromotionLockStateLowerEnv struct {
	PromotionId *string `json:"promotionId,omitempty"`
	ProxyState  *string `json:"proxyState,omitempty"`
	State       *string `json:"state,omitempty"`
}

// NewPromotionLockStateLowerEnv instantiates a new PromotionLockStateLowerEnv object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotionLockStateLowerEnv() *PromotionLockStateLowerEnv {
	this := PromotionLockStateLowerEnv{}
	return &this
}

// NewPromotionLockStateLowerEnvWithDefaults instantiates a new PromotionLockStateLowerEnv object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotionLockStateLowerEnvWithDefaults() *PromotionLockStateLowerEnv {
	this := PromotionLockStateLowerEnv{}
	return &this
}

// GetPromotionId returns the PromotionId field value if set, zero value otherwise.
func (o *PromotionLockStateLowerEnv) GetPromotionId() string {
	if o == nil || IsNil(o.PromotionId) {
		var ret string
		return ret
	}
	return *o.PromotionId
}

// GetPromotionIdOk returns a tuple with the PromotionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionLockStateLowerEnv) GetPromotionIdOk() (*string, bool) {
	if o == nil || IsNil(o.PromotionId) {
		return nil, false
	}
	return o.PromotionId, true
}

// HasPromotionId returns a boolean if a field has been set.
func (o *PromotionLockStateLowerEnv) HasPromotionId() bool {
	if o != nil && !IsNil(o.PromotionId) {
		return true
	}

	return false
}

// SetPromotionId gets a reference to the given string and assigns it to the PromotionId field.
func (o *PromotionLockStateLowerEnv) SetPromotionId(v string) {
	o.PromotionId = &v
}

// GetProxyState returns the ProxyState field value if set, zero value otherwise.
func (o *PromotionLockStateLowerEnv) GetProxyState() string {
	if o == nil || IsNil(o.ProxyState) {
		var ret string
		return ret
	}
	return *o.ProxyState
}

// GetProxyStateOk returns a tuple with the ProxyState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionLockStateLowerEnv) GetProxyStateOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyState) {
		return nil, false
	}
	return o.ProxyState, true
}

// HasProxyState returns a boolean if a field has been set.
func (o *PromotionLockStateLowerEnv) HasProxyState() bool {
	if o != nil && !IsNil(o.ProxyState) {
		return true
	}

	return false
}

// SetProxyState gets a reference to the given string and assigns it to the ProxyState field.
func (o *PromotionLockStateLowerEnv) SetProxyState(v string) {
	o.ProxyState = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *PromotionLockStateLowerEnv) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionLockStateLowerEnv) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *PromotionLockStateLowerEnv) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *PromotionLockStateLowerEnv) SetState(v string) {
	o.State = &v
}

func (o PromotionLockStateLowerEnv) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromotionLockStateLowerEnv) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PromotionId) {
		toSerialize["promotionId"] = o.PromotionId
	}
	if !IsNil(o.ProxyState) {
		toSerialize["proxyState"] = o.ProxyState
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullablePromotionLockStateLowerEnv struct {
	value *PromotionLockStateLowerEnv
	isSet bool
}

func (v NullablePromotionLockStateLowerEnv) Get() *PromotionLockStateLowerEnv {
	return v.value
}

func (v *NullablePromotionLockStateLowerEnv) Set(val *PromotionLockStateLowerEnv) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotionLockStateLowerEnv) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotionLockStateLowerEnv) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotionLockStateLowerEnv(val *PromotionLockStateLowerEnv) *NullablePromotionLockStateLowerEnv {
	return &NullablePromotionLockStateLowerEnv{value: val, isSet: true}
}

func (v NullablePromotionLockStateLowerEnv) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotionLockStateLowerEnv) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
