/*
PingOne Advanced Identity Cloud API

## Introduction The PingOne Advanced Identity Cloud REST API lets you manage your Advanced Identity Cloud tenants. The API exposes access management and identity management endpoints, with additional endpoints specific to Advanced Identity Cloud tenant environments.<br /><br /> We are now publishing the API spec in OpenAPI 3.0. For the legacy Swagger 2.0 spec, please download [swagger.yaml](swagger.yaml), but note that it may not contain all new functionality.<br /><br /> For full PingOne Advanced Identity Cloud documentation, please visit [the docs website](https://docs.pingidentity.com/pingoneaic/latest/). ## Authenticating to the API The PingOne Advanced Identity Cloud REST API has two different authentication methods:   - [API key and secret](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-api-key-and-secret.html): used for tenant read-only operations  - [Access token](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-access-token.html): used for access management operations, identity management operations or tenant write operations  For a summary of how to use these authentication methods, refer to [Authenticate to Advanced Identity Cloud REST API](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-overview.html).

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aic

import (
	"encoding/json"
)

// checks if the CName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CName{}

// CName struct for CName
type CName struct {
	// The canonical name of the domain to be validated.
	Name string `json:"name"`
}

// NewCName instantiates a new CName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCName(name string) *CName {
	this := CName{}
	this.Name = name
	return &this
}

// NewCNameWithDefaults instantiates a new CName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCNameWithDefaults() *CName {
	this := CName{}
	return &this
}

// GetName returns the Name field value
func (o *CName) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CName) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CName) SetName(v string) {
	o.Name = v
}

func (o CName) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableCName struct {
	value *CName
	isSet bool
}

func (v NullableCName) Get() *CName {
	return v.value
}

func (v *NullableCName) Set(val *CName) {
	v.value = val
	v.isSet = true
}

func (v NullableCName) IsSet() bool {
	return v.isSet
}

func (v *NullableCName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCName(val *CName) *NullableCName {
	return &NullableCName{value: val, isSet: true}
}

func (v NullableCName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
