/*
PingOne Advanced Identity Cloud API

## Introduction The PingOne Advanced Identity Cloud REST API lets you manage your Advanced Identity Cloud tenants. The API exposes access management and identity management endpoints, with additional endpoints specific to Advanced Identity Cloud tenant environments.<br /><br /> We are now publishing the API spec in OpenAPI 3.0. For the legacy Swagger 2.0 spec, please download [swagger.yaml](swagger.yaml), but note that it may not contain all new functionality.<br /><br /> For full PingOne Advanced Identity Cloud documentation, please visit [the docs website](https://docs.pingidentity.com/pingoneaic/latest/). ## Authenticating to the API The PingOne Advanced Identity Cloud REST API has two different authentication methods:   - [API key and secret](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-api-key-and-secret.html): used for tenant read-only operations  - [Access token](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-access-token.html): used for access management operations, identity management operations or tenant write operations  For a summary of how to use these authentication methods, refer to [Authenticate to Advanced Identity Cloud REST API](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-overview.html).

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aic

import (
	"encoding/json"
)

// checks if the PromotionStart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromotionStart{}

// PromotionStart struct for PromotionStart
type PromotionStart struct {
	Result *string `json:"result,omitempty"`
}

// NewPromotionStart instantiates a new PromotionStart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotionStart() *PromotionStart {
	this := PromotionStart{}
	return &this
}

// NewPromotionStartWithDefaults instantiates a new PromotionStart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotionStartWithDefaults() *PromotionStart {
	this := PromotionStart{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *PromotionStart) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionStart) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *PromotionStart) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *PromotionStart) SetResult(v string) {
	o.Result = &v
}

func (o PromotionStart) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromotionStart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullablePromotionStart struct {
	value *PromotionStart
	isSet bool
}

func (v NullablePromotionStart) Get() *PromotionStart {
	return v.value
}

func (v *NullablePromotionStart) Set(val *PromotionStart) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotionStart) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotionStart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotionStart(val *PromotionStart) *NullablePromotionStart {
	return &NullablePromotionStart{value: val, isSet: true}
}

func (v NullablePromotionStart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotionStart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
