/*
PingOne Advanced Identity Cloud API

## Introduction The PingOne Advanced Identity Cloud REST API lets you manage your Advanced Identity Cloud tenants. The API exposes access management and identity management endpoints, with additional endpoints specific to Advanced Identity Cloud tenant environments.<br /><br /> We are now publishing the API spec in OpenAPI 3.0. For the legacy Swagger 2.0 spec, please download [swagger.yaml](swagger.yaml), but note that it may not contain all new functionality.<br /><br /> For full PingOne Advanced Identity Cloud documentation, please visit [the docs website](https://docs.pingidentity.com/pingoneaic/latest/). ## Authenticating to the API The PingOne Advanced Identity Cloud REST API has two different authentication methods:   - [API key and secret](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-api-key-and-secret.html): used for tenant read-only operations  - [Access token](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-access-token.html): used for access management operations, identity management operations or tenant write operations  For a summary of how to use these authentication methods, refer to [Authenticate to Advanced Identity Cloud REST API](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-overview.html).

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aic

import (
	"encoding/json"
)

// checks if the RollbackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RollbackRequest{}

// RollbackRequest struct for RollbackRequest
type RollbackRequest struct {
	// The name of the admin user who initiated the promotion
	Promoter *string `json:"promoter,omitempty"`
	// Promoter specified note to make it easier for them to identify what was promoted
	PromotionDescription *string `json:"promotionDescription,omitempty"`
	// A boolean denoting whether or not to automatically unlock the environments after a successful promotion
	UnlockEnvironmentsAfterPromotion *bool `json:"unlockEnvironmentsAfterPromotion,omitempty"`
	// A string denoting the Zendesk ticket reference to be added to the promotion commit message
	ZendeskTicketReference *string `json:"zendeskTicketReference,omitempty"`
}

// NewRollbackRequest instantiates a new RollbackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRollbackRequest() *RollbackRequest {
	this := RollbackRequest{}
	return &this
}

// NewRollbackRequestWithDefaults instantiates a new RollbackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRollbackRequestWithDefaults() *RollbackRequest {
	this := RollbackRequest{}
	return &this
}

// GetPromoter returns the Promoter field value if set, zero value otherwise.
func (o *RollbackRequest) GetPromoter() string {
	if o == nil || IsNil(o.Promoter) {
		var ret string
		return ret
	}
	return *o.Promoter
}

// GetPromoterOk returns a tuple with the Promoter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetPromoterOk() (*string, bool) {
	if o == nil || IsNil(o.Promoter) {
		return nil, false
	}
	return o.Promoter, true
}

// HasPromoter returns a boolean if a field has been set.
func (o *RollbackRequest) HasPromoter() bool {
	if o != nil && !IsNil(o.Promoter) {
		return true
	}

	return false
}

// SetPromoter gets a reference to the given string and assigns it to the Promoter field.
func (o *RollbackRequest) SetPromoter(v string) {
	o.Promoter = &v
}

// GetPromotionDescription returns the PromotionDescription field value if set, zero value otherwise.
func (o *RollbackRequest) GetPromotionDescription() string {
	if o == nil || IsNil(o.PromotionDescription) {
		var ret string
		return ret
	}
	return *o.PromotionDescription
}

// GetPromotionDescriptionOk returns a tuple with the PromotionDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetPromotionDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.PromotionDescription) {
		return nil, false
	}
	return o.PromotionDescription, true
}

// HasPromotionDescription returns a boolean if a field has been set.
func (o *RollbackRequest) HasPromotionDescription() bool {
	if o != nil && !IsNil(o.PromotionDescription) {
		return true
	}

	return false
}

// SetPromotionDescription gets a reference to the given string and assigns it to the PromotionDescription field.
func (o *RollbackRequest) SetPromotionDescription(v string) {
	o.PromotionDescription = &v
}

// GetUnlockEnvironmentsAfterPromotion returns the UnlockEnvironmentsAfterPromotion field value if set, zero value otherwise.
func (o *RollbackRequest) GetUnlockEnvironmentsAfterPromotion() bool {
	if o == nil || IsNil(o.UnlockEnvironmentsAfterPromotion) {
		var ret bool
		return ret
	}
	return *o.UnlockEnvironmentsAfterPromotion
}

// GetUnlockEnvironmentsAfterPromotionOk returns a tuple with the UnlockEnvironmentsAfterPromotion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetUnlockEnvironmentsAfterPromotionOk() (*bool, bool) {
	if o == nil || IsNil(o.UnlockEnvironmentsAfterPromotion) {
		return nil, false
	}
	return o.UnlockEnvironmentsAfterPromotion, true
}

// HasUnlockEnvironmentsAfterPromotion returns a boolean if a field has been set.
func (o *RollbackRequest) HasUnlockEnvironmentsAfterPromotion() bool {
	if o != nil && !IsNil(o.UnlockEnvironmentsAfterPromotion) {
		return true
	}

	return false
}

// SetUnlockEnvironmentsAfterPromotion gets a reference to the given bool and assigns it to the UnlockEnvironmentsAfterPromotion field.
func (o *RollbackRequest) SetUnlockEnvironmentsAfterPromotion(v bool) {
	o.UnlockEnvironmentsAfterPromotion = &v
}

// GetZendeskTicketReference returns the ZendeskTicketReference field value if set, zero value otherwise.
func (o *RollbackRequest) GetZendeskTicketReference() string {
	if o == nil || IsNil(o.ZendeskTicketReference) {
		var ret string
		return ret
	}
	return *o.ZendeskTicketReference
}

// GetZendeskTicketReferenceOk returns a tuple with the ZendeskTicketReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetZendeskTicketReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.ZendeskTicketReference) {
		return nil, false
	}
	return o.ZendeskTicketReference, true
}

// HasZendeskTicketReference returns a boolean if a field has been set.
func (o *RollbackRequest) HasZendeskTicketReference() bool {
	if o != nil && !IsNil(o.ZendeskTicketReference) {
		return true
	}

	return false
}

// SetZendeskTicketReference gets a reference to the given string and assigns it to the ZendeskTicketReference field.
func (o *RollbackRequest) SetZendeskTicketReference(v string) {
	o.ZendeskTicketReference = &v
}

func (o RollbackRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RollbackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Promoter) {
		toSerialize["promoter"] = o.Promoter
	}
	if !IsNil(o.PromotionDescription) {
		toSerialize["promotionDescription"] = o.PromotionDescription
	}
	if !IsNil(o.UnlockEnvironmentsAfterPromotion) {
		toSerialize["unlockEnvironmentsAfterPromotion"] = o.UnlockEnvironmentsAfterPromotion
	}
	if !IsNil(o.ZendeskTicketReference) {
		toSerialize["zendeskTicketReference"] = o.ZendeskTicketReference
	}
	return toSerialize, nil
}

type NullableRollbackRequest struct {
	value *RollbackRequest
	isSet bool
}

func (v NullableRollbackRequest) Get() *RollbackRequest {
	return v.value
}

func (v *NullableRollbackRequest) Set(val *RollbackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRollbackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRollbackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRollbackRequest(val *RollbackRequest) *NullableRollbackRequest {
	return &NullableRollbackRequest{value: val, isSet: true}
}

func (v NullableRollbackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRollbackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
