/*
PingOne Advanced Identity Cloud API

## Introduction The PingOne Advanced Identity Cloud REST API lets you manage your Advanced Identity Cloud tenants. The API exposes access management and identity management endpoints, with additional endpoints specific to Advanced Identity Cloud tenant environments.<br /><br /> We are now publishing the API spec in OpenAPI 3.0. For the legacy Swagger 2.0 spec, please download [swagger.yaml](swagger.yaml), but note that it may not contain all new functionality.<br /><br /> For full PingOne Advanced Identity Cloud documentation, please visit [the docs website](https://docs.pingidentity.com/pingoneaic/latest/). ## Authenticating to the API The PingOne Advanced Identity Cloud REST API has two different authentication methods:   - [API key and secret](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-api-key-and-secret.html): used for tenant read-only operations  - [Access token](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-access-token.html): used for access management operations, identity management operations or tenant write operations  For a summary of how to use these authentication methods, refer to [Authenticate to Advanced Identity Cloud REST API](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-overview.html).

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identitycloud

import (
	"encoding/json"
)

// checks if the UpdateCertificateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCertificateRequest{}

// UpdateCertificateRequest struct for UpdateCertificateRequest
type UpdateCertificateRequest struct {
	// The active status of the certificate. Set this to true for the certificate to actively be served.
	Active *bool `json:"active,omitempty"`
}

// NewUpdateCertificateRequest instantiates a new UpdateCertificateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCertificateRequest() *UpdateCertificateRequest {
	this := UpdateCertificateRequest{}
	return &this
}

// NewUpdateCertificateRequestWithDefaults instantiates a new UpdateCertificateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCertificateRequestWithDefaults() *UpdateCertificateRequest {
	this := UpdateCertificateRequest{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *UpdateCertificateRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCertificateRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *UpdateCertificateRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *UpdateCertificateRequest) SetActive(v bool) {
	o.Active = &v
}

func (o UpdateCertificateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCertificateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	return toSerialize, nil
}

type NullableUpdateCertificateRequest struct {
	value *UpdateCertificateRequest
	isSet bool
}

func (v NullableUpdateCertificateRequest) Get() *UpdateCertificateRequest {
	return v.value
}

func (v *NullableUpdateCertificateRequest) Set(val *UpdateCertificateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCertificateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCertificateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCertificateRequest(val *UpdateCertificateRequest) *NullableUpdateCertificateRequest {
	return &NullableUpdateCertificateRequest{value: val, isSet: true}
}

func (v NullableUpdateCertificateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCertificateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
