/*
PingOne Advanced Identity Cloud API

## Introduction The PingOne Advanced Identity Cloud REST API lets you manage your Advanced Identity Cloud tenants. The API exposes access management and identity management endpoints, with additional endpoints specific to Advanced Identity Cloud tenant environments.<br /><br /> We are now publishing the API spec in OpenAPI 3.0. For the legacy Swagger 2.0 spec, please download [swagger.yaml](swagger.yaml), but note that it may not contain all new functionality.<br /><br /> For full PingOne Advanced Identity Cloud documentation, please visit [the docs website](https://docs.pingidentity.com/pingoneaic/latest/). ## Authenticating to the API The PingOne Advanced Identity Cloud REST API has two different authentication methods:   - [API key and secret](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-api-key-and-secret.html): used for tenant read-only operations  - [Access token](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-with-access-token.html): used for access management operations, identity management operations or tenant write operations  For a summary of how to use these authentication methods, refer to [Authenticate to Advanced Identity Cloud REST API](https://docs.pingidentity.com/pingoneaic/latest/developer-docs/authenticate-to-rest-api-overview.html).

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identitycloud

import (
	"encoding/json"
)

// checks if the FederationEnforcement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FederationEnforcement{}

// FederationEnforcement struct for FederationEnforcement
type FederationEnforcement struct {
	Groups string `json:"groups"`
}

// NewFederationEnforcement instantiates a new FederationEnforcement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFederationEnforcement(groups string) *FederationEnforcement {
	this := FederationEnforcement{}
	this.Groups = groups
	return &this
}

// NewFederationEnforcementWithDefaults instantiates a new FederationEnforcement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFederationEnforcementWithDefaults() *FederationEnforcement {
	this := FederationEnforcement{}
	return &this
}

// GetGroups returns the Groups field value
func (o *FederationEnforcement) GetGroups() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *FederationEnforcement) GetGroupsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Groups, true
}

// SetGroups sets field value
func (o *FederationEnforcement) SetGroups(v string) {
	o.Groups = v
}

func (o FederationEnforcement) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FederationEnforcement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["groups"] = o.Groups
	return toSerialize, nil
}

type NullableFederationEnforcement struct {
	value *FederationEnforcement
	isSet bool
}

func (v NullableFederationEnforcement) Get() *FederationEnforcement {
	return v.value
}

func (v *NullableFederationEnforcement) Set(val *FederationEnforcement) {
	v.value = val
	v.isSet = true
}

func (v NullableFederationEnforcement) IsSet() bool {
	return v.isSet
}

func (v *NullableFederationEnforcement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFederationEnforcement(val *FederationEnforcement) *NullableFederationEnforcement {
	return &NullableFederationEnforcement{value: val, isSet: true}
}

func (v NullableFederationEnforcement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFederationEnforcement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
